name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - 'build/*'
    - '.build/*'
    - '.ccls-cache/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies for Emacs.
      run: >
        sudo apt-get update \
          && sudo apt-get install -y \
             build-essential \
             git \
             libtiff5-dev \
             libgtk-3-dev \
             libjansson-dev \
             libncurses-dev \
             libgnutls28-dev \
             automake

    - name: Cache Emacs.
      id: cache-emacs
      uses: actions/cache@v2
      with:
        path: /opt/emacs
        key: ${{ runner.os }}-emacs

    - name: Build Emacs.
      if: steps.cache-emacs.outputs.cache-hit != 'true'
      run: >
        cd /opt \
          && git clone --depth 1 --branch emacs-27 git://git.sv.gnu.org/emacs.git \
          && cd emacs \
          && ./autogen.sh \
          && ./configure \
            --without-toolkit-scroll-bars \
            --without-xaw3d --without-xim \
            --without-compress-install \
            --with-sound=no \
            --without-pop \
            --without-makeinfo \
            --without-gconf \
            --without-gsettings \
            --without-selinux \
            --without-gpm \
            --with-rsvg --with-gnutls \
            --with-xpm=ifavailable \
            --with-gif=ifavailable \
            --with-json \
          && make

    - name: Install Emacs.
      run: cd /opt/emacs && sudo make install

    - name: Install dependencies for jq-impl.
      run: >
        sudo apt-get update \
          && sudo apt-get install -y \
            build-essential \
            cmake \
            autoconf \
            libtool \
          && curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python

    - name: Build jq-impl.
      run: >
        mkdir build && cd build \
          && cmake .. && cmake --build .

    - name: Run tests.
      run: >
        export PATH="${HOME}/.cask/bin:$PATH" \
          && export EMACSLOADPATH="$EMACSLOADPATH:.:./build" \
          && cask install \
          && cask exec ert-runner
