name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 27.1
    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - name: Install emacs-module.h
      run: sudo cp -v $HOME/.nix-profile/include/emacs-module.h /usr/include/
    - name: Link liblzma
      run: sudo ln -s /usr/lib/x86_64-linux-gnu/liblzma.so /usr/lib/x86_64-linux-gnu/liblzma.so.5
    - name: Build jq-impl
      run: mkdir build && cd build && cmake .. && cmake --build .
    - name: Byte-compile jq.el
      run: >
        LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu" \
          emacs -Q --batch -L build -f batch-byte-compile jq.el
    - name: Run tests
      run: >
        LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu" \
          emacs -Q --batch -L build -L . -l test/jq-test.el -f ert-run-tests-batch-and-exit
